# Generated by Django 2.2.9 on 2020-02-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_goal_data_man',
            name='emp_id',
            field=models.IntegerField(default=0),
        ),
    ]
