# Generated by Django 2.2.9 on 2020-02-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miss_management', '0002_emp_goal_data_man_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_goal_data_man',
            name='man_comment',
        ),
    ]
