# Generated by Django 2.2.9 on 2020-02-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss_management', '0003_remove_emp_goal_data_man_man_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('job_title', models.CharField(default='NA', max_length=25)),
                ('last_ap_date', models.CharField(max_length=100)),
                ('reporting_mail', models.EmailField(max_length=50)),
                ('doj', models.CharField(max_length=100)),
                ('evalute_by', models.CharField(max_length=100)),
            ],
        ),
    ]
