# Generated by Django 2.2.6 on 2020-02-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('joining_date', models.DateTimeField()),
                ('manager_email', models.CharField(max_length=50)),
                ('managing_department', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
